/**
 * sidestep.test.ts - the version 3 sidestep against the spec's reference.
 *
 * The golden vectors in fixtures/sidestep_v3.json were generated by the spec
 * repository's sidestep-reference.py (scripts/sidestep-vectors.py names the
 * commit) and MUST match exactly: seed prefixes, roots, the attempt count,
 * the nonce, G, sampled indices and every opening.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { bytesToHex, hexToBytes, sha256 } from '../src/cantor.js'
import { coordToXyz, hexToCoord } from '../src/coords.js'
import { alignedBase, findLcaHeight } from '../src/movement.js'
import { GRANDFATHERED_V2_SIDESTEPS } from '../src/grandfathered_v2_sidesteps.js'
import {
  AXIS_BYTE,
  SIDESTEP_GRIND_DOMAIN,
  SIDESTEP_SAMPLES,
  computeAxisMerkleRoot,
  computeSidestepProof,
  decodeNonce,
  decodeOpenings,
  encodeNonce,
  encodeOpenings,
  estimateSidestepCost,
  findSidestepNonce,
  isGrandfatheredV2Sidestep,
  leafHasher,
  meetsPrice,
  merkleLeaf,
  merkleParent,
  sampleIndices,
  seedPrefix,
  sidestepAttempts,
  sidestepGrindHash,
  sidestepLanding,
  validCrossing,
  verifyAxisOpenings,
  verifyMerkleInclusion,
  verifySidestepLevel1,
  type SidestepClaim,
  type SidestepProof,
} from '../src/sidestep.js'

interface Vector {
  name: string
  prev: string
  src: [string, string, string]
  dst: [string, string, string]
  heights: [number, number, number]
  prefixes: string[]
  roots: [string, string, string]
  attempts: string
  nonce: string
  G: string
  samples: number[][]
  openings: string[][][]
}
const VECTORS: Vector[] = JSON.parse(readFileSync(new URL('./fixtures/sidestep_v3.json', import.meta.url), 'utf8')).vectors
const vector = (name: string): Vector => VECTORS.find((v) => v.name === name)!
const ZERO = new Uint8Array(32)
const RANGE = new Uint8Array(32).map((_, i) => i)
const AXES = ['x', 'y', 'z'] as const
const TWO_256 = 1n << 256n
const int256 = (n: bigint): Uint8Array => hexToBytes(n.toString(16).padStart(64, '0'))

/** Every level of a small tree, leaves first, to take any path from. */
function levelsOf(prefix: Uint8Array, base: bigint, height: number): Uint8Array[][] {
  const levels = [Array.from({ length: 2 ** height }, (_, i) => merkleLeaf(prefix, base + BigInt(i)))]
  while (levels[levels.length - 1].length > 1) {
    const below = levels[levels.length - 1]
    levels.push(Array.from({ length: below.length / 2 }, (_, j) => merkleParent(below[2 * j], below[2 * j + 1])))
  }
  return levels
}
const pathAt = (levels: Uint8Array[][], index: number): Uint8Array[] =>
  levels.slice(0, -1).map((level, depth) => level[Math.floor(index / 2 ** depth) ^ 1])

/** Version 2's sample positions, drawn from the axis root under the V1 sample domain. */
function v2Samples(root: Uint8Array, axisByte: number, height: number): number[] {
  const domain = new TextEncoder().encode('CYBERSPACE_SIDESTEP_SAMPLE_V1')
  return Array.from({ length: SIDESTEP_SAMPLES }, (_, i) => {
    const h = sha256(new Uint8Array([...domain, ...root, axisByte, 0, 0, 0, i]))
    return Number(BigInt('0x' + bytesToHex(h)) % (1n << BigInt(height)))
  })
}

/** The claim an event built from `proof` would make, `mn` tag included. */
function claimOf(proof: SidestepProof, from: bigint[], to: bigint[], prev: string): SidestepClaim {
  return {
    from: { x: from[0], y: from[1], z: from[2] },
    to: { x: to[0], y: to[1], z: to[2] },
    plane: 0,
    previousEventIdHex: prev,
    merkleRoots: [bytesToHex(proof.merkleX), bytesToHex(proof.merkleY), bytesToHex(proof.merkleZ)],
    openings: [encodeOpenings(proof.openings.x), encodeOpenings(proof.openings.y), encodeOpenings(proof.openings.z)],
    nonce: encodeNonce(proof.nonce),
    lcaHeights: proof.lcaHeights,
    proofHash: proof.proofHash,
  }
}

describe('seedPrefix', () => {
  it('is the domain, the previous id, the axis byte and the pad: one block', () => {
    for (const v of VECTORS) {
      AXES.forEach((_, ax) => expect(bytesToHex(seedPrefix(hexToBytes(v.prev), ax))).toBe(v.prefixes[ax]))
    }
    expect(seedPrefix(ZERO, 0).length).toBe(64)
    expect(() => seedPrefix(new Uint8Array(31), 0)).toThrow()
  })
})

describe('leafHasher', () => {
  it('resumes from the midstate to the same hash as one plain SHA-256', () => {
    const prefix = seedPrefix(RANGE, 2)
    const leaf = leafHasher(prefix)
    for (const value of [0n, 1n, 255n, 256n, 1n << 40n, (1n << 85n) - 1n]) {
      expect(bytesToHex(leaf(value))).toBe(bytesToHex(merkleLeaf(prefix, value)))
    }
  })
})

describe('the golden crossing (spec 6.10, sidestep-reference.py)', () => {
  // previous_event_id = 32 zero bytes; z crosses the h12 wall from the source side.
  const base = (0x1234567n >> 12n) << 12n
  const proof = computeSidestepProof(5n, 7n, base + (1n << 11n) - 1n, 5n, 7n, base + (1n << 11n), 0, bytesToHex(ZERO))

  it('prices the crossing at A = 512 and finds nonce 175 and its G', () => {
    expect(sidestepAttempts(proof.lcaHeights)).toBe(512n)
    expect(proof.nonce).toBe(175n)
    expect(bytesToHex(proof.G)).toBe('0067d4a60e171a3f6007da903f999c0eb441115369fa2d07f9424af4dd5f985a')
    expect(encodeNonce(proof.nonce)).toBe('00000000000000af')
  })
  it('draws 2113 as the first sample on z', () => {
    expect(sampleIndices(proof.G, AXIS_BYTE.z, 12)[0]).toBe(2113)
  })
  it('keeps the version 2 axis roots', () => {
    // A trivial axis contributes its single seeded leaf to G.
    expect(bytesToHex(proof.merkleX)).toBe(bytesToHex(merkleLeaf(seedPrefix(ZERO, 0), 5n)))
    const at = (prev: Uint8Array, axis: number, v1: bigint, v2: bigint) => bytesToHex(computeAxisMerkleRoot(seedPrefix(prev, axis), axis, v1, v2).root)
    expect(at(ZERO, 0, 0n, 0n)).toBe('803e23af5b006f6542e43cb30a70e0229916586105eb230e5d8796984d5b0901')
    expect(at(ZERO, 2, base, base + (1n << 4n))).toBe('202ede33045254297d335033c68b2fa05e6a47be1756abe7fee8caeedd89dcd6')
    expect(at(RANGE, 1, 1n << 40n, (1n << 40n) + (1n << 8n))).toBe('badf31e4bf617b2cddaa7f5b560ead66ed34198523a2b8ae4f45b624103cda92')
  })
  it('takes the first nonce: none below 175 meets the price', () => {
    const roots = [proof.merkleX, proof.merkleY, proof.merkleZ]
    for (let n = 0n; n < 175n; n++) expect(meetsPrice(sidestepGrindHash(ZERO, roots, n), 512n)).toBe(false)
    expect(meetsPrice(sidestepGrindHash(ZERO, roots, 175n), 512n)).toBe(true)
  })
})

describe('the reference vectors', () => {
  for (const v of VECTORS) {
    it(`${v.name} (h${v.heights.join('/h')}): roots, A, nonce, G, samples and every opening`, () => {
      const prev = hexToBytes(v.prev)
      const src = v.src.map(BigInt), dst = v.dst.map(BigInt)
      const trees = AXES.map((_, ax) => computeAxisMerkleRoot(seedPrefix(prev, ax), ax, src[ax], dst[ax]))
      expect(trees.map((t) => t.height)).toEqual(v.heights)
      expect(trees.map((t) => bytesToHex(t.root))).toEqual(v.roots)
      const attempts = sidestepAttempts(v.heights)
      expect(attempts).toBe(BigInt(v.attempts))
      const found = findSidestepNonce(prev, trees.map((t) => t.root), attempts)!
      expect(found.nonce).toBe(BigInt(v.nonce))
      expect(bytesToHex(found.G)).toBe(v.G)
      expect(bytesToHex(sidestepGrindHash(prev, trees.map((t) => t.root), found.nonce))).toBe(v.G)
      trees.forEach((t, ax) => {
        expect(sampleIndices(found.G, ax, t.height)).toEqual(v.samples[ax])
        const openings = t.openingsFor(found.G)
        expect(openings.map((p) => p.map(bytesToHex))).toEqual(v.openings[ax])
        expect(verifyAxisOpenings(seedPrefix(prev, ax), ax, src[ax], dst[ax], t.root, openings, found.G)).toBe(true)
      })
    })
  }

  it('come out of computeSidestepProof whole', () => {
    for (const v of VECTORS) {
      const [x1, y1, z1] = v.src.map(BigInt), [x2, y2, z2] = v.dst.map(BigInt)
      const p = computeSidestepProof(x1, y1, z1, x2, y2, z2, 0, v.prev)
      expect([p.merkleX, p.merkleY, p.merkleZ].map(bytesToHex)).toEqual(v.roots)
      expect(p.nonce).toBe(BigInt(v.nonce))
      expect(bytesToHex(p.G)).toBe(v.G)
      expect([p.openings.x, p.openings.y, p.openings.z].map((o) => o.map((path) => path.map(bytesToHex)))).toEqual(v.openings)
    }
  })
})

describe('the re-roll price (spec 6.10)', () => {
  it('charges the leaves of the moving axes over eight, rounded up, at least 1', () => {
    expect(sidestepAttempts([0, 0, 0])).toBe(1n)
    expect(sidestepAttempts([1, 0, 0])).toBe(1n)
    expect(sidestepAttempts([0, 0, 12])).toBe(512n)
    expect(sidestepAttempts([5, 0, 9])).toBe(68n) // 544 leaves
    expect(sidestepAttempts([3, 2, 1])).toBe(2n) // 14 leaves
    expect(sidestepAttempts([85, 85, 85])).toBe(3n << 82n)
  })

  it('compares G x A against 2^256 exactly', () => {
    for (const A of [3n, 68n, 512n, 3n << 82n]) {
      const T = (TWO_256 - 1n) / A
      expect(meetsPrice(int256(T), A)).toBe(true)
      expect(meetsPrice(int256(T + 1n), A)).toBe(false)
    }
    // A = 1 is a free crossing: every G meets it.
    expect(meetsPrice(int256(TWO_256 - 1n), 1n)).toBe(true)
    expect(() => meetsPrice(int256(0n), 0n)).toThrow()
  })

  it('searches with the same verdict as meetsPrice, nonce by nonce', () => {
    // An odd price, so the byte threshold the search uses is not a power of two.
    const roots = [sha256(new Uint8Array([1])), sha256(new Uint8Array([2])), sha256(new Uint8Array([3]))]
    for (let n = 0n; n < 300n; n++) {
      const hit = findSidestepNonce(RANGE, roots, 3n, { start: n, end: n + 1n })
      expect(hit !== null).toBe(meetsPrice(sidestepGrindHash(RANGE, roots, n), 3n))
    }
  })

  it('searches any range, so workers can split it', () => {
    const v = vector('golden-z-h12')
    const roots = v.roots.map(hexToBytes)
    expect(findSidestepNonce(ZERO, roots, 512n, { end: 175n })).toBeNull()
    expect(findSidestepNonce(ZERO, roots, 512n, { start: 175n, end: 176n })!.nonce).toBe(175n)
    const next = findSidestepNonce(ZERO, roots, 512n, { start: 176n })!
    expect(next.nonce).toBeGreaterThan(175n)
    for (let n = 176n; n < next.nonce; n++) expect(meetsPrice(sidestepGrindHash(ZERO, roots, n), 512n)).toBe(false)
    expect(meetsPrice(next.G, 512n)).toBe(true)
    expect(() => findSidestepNonce(ZERO, roots, 512n, { end: (1n << 64n) + 1n })).toThrow()
  })

  it('puts the nonce in the first of three blocks, and refuses what is not 64 bits', () => {
    expect(SIDESTEP_GRIND_DOMAIN.length).toBe(28)
    expect(SIDESTEP_GRIND_DOMAIN.length + 8).toBeLessThanOrEqual(64)
    expect(() => sidestepGrindHash(ZERO, [ZERO, ZERO, ZERO], -1n)).toThrow()
    expect(() => sidestepGrindHash(ZERO, [ZERO, ZERO, ZERO], 1n << 64n)).toThrow()
    expect(() => sidestepGrindHash(ZERO, [ZERO, ZERO], 0n)).toThrow()
    expect(() => sidestepGrindHash(new Uint8Array(31), [ZERO, ZERO, ZERO], 0n)).toThrow()
  })

  it('reports search progress that never goes backwards and ends at 1', () => {
    const seen: number[] = []
    findSidestepNonce(ZERO, vector('golden-z-h12').roots.map(hexToBytes), 512n, { onProgress: (f) => seen.push(f) })
    expect(seen.length).toBeGreaterThan(1)
    expect(seen.at(-1)).toBe(1)
    for (let i = 1; i < seen.length; i++) expect(seen[i]).toBeGreaterThanOrEqual(seen[i - 1])
  })
})

describe('the mn tag (spec 8.5)', () => {
  it('is exactly 16 lowercase hex characters, big-endian', () => {
    expect(encodeNonce(0n)).toBe('0000000000000000')
    expect(encodeNonce(175n)).toBe('00000000000000af')
    expect(encodeNonce((1n << 64n) - 1n)).toBe('ffffffffffffffff')
    expect(() => encodeNonce(-1n)).toThrow()
    expect(() => encodeNonce(1n << 64n)).toThrow()
    for (const n of [0n, 175n, 1n << 40n, (1n << 64n) - 1n]) expect(decodeNonce(encodeNonce(n))).toBe(n)
  })
  it('rejects anything else', () => {
    for (const bad of ['00000000000000AF', '0000000000000af', '000000000000000af', '0x000000000000af', '', ' 00000000000000af']) {
      expect(decodeNonce(bad)).toBeNull()
    }
  })
})

describe('computeAxisMerkleRoot', () => {
  const G = sha256(new TextEncoder().encode('any G'))

  it('matches a hand-built height-2 tree', () => {
    const prefix = seedPrefix(ZERO, 0)
    const h = [0n, 1n, 2n, 3n].map((n) => merkleLeaf(prefix, n))
    const expected = merkleParent(merkleParent(h[0], h[1]), merkleParent(h[2], h[3]))
    const r = computeAxisMerkleRoot(prefix, 0, 1n, 2n)
    expect(bytesToHex(r.root)).toBe(bytesToHex(expected))
    const openings = r.openingsFor(G)
    // Destination is leaf 2 (left of the right pair): siblings are h3 then p01.
    expect(bytesToHex(openings[0][0])).toBe(bytesToHex(h[3]))
    expect(bytesToHex(openings[0][1])).toBe(bytesToHex(merkleParent(h[0], h[1])))
    expect(openings).toHaveLength(SIDESTEP_SAMPLES + 1)
  })

  it('assembles the same openings when the height is above the kept levels', () => {
    // h18: two levels rebuilt under each opened leaf, the rest from what was kept.
    const prefix = seedPrefix(RANGE, 1)
    const base = 5n << 18n
    const v1 = base + (1n << 17n) - 1n, v2 = base + (1n << 17n)
    const r = computeAxisMerkleRoot(prefix, 1, v1, v2)
    expect(r.height).toBe(18)
    const openings = r.openingsFor(G)
    expect(verifyAxisOpenings(prefix, 1, v1, v2, r.root, openings, G)).toBe(true)
    // Every sampled path is the path of its own leaf, checked from scratch.
    const samples = sampleIndices(G, 1, 18)
    samples.forEach((idx, i) => expect(verifyMerkleInclusion(prefix, base + BigInt(idx), openings[i + 1], r.root, 18, base)).toBe(true))
  })

  it('handles trivial axes as a single seeded leaf with no openings', () => {
    const prefix = seedPrefix(ZERO, 0)
    const r = computeAxisMerkleRoot(prefix, 0, 100n, 100n)
    expect(r.height).toBe(0)
    expect(r.openingsFor(G)).toEqual([])
    expect(bytesToHex(r.root)).toBe(bytesToHex(merkleLeaf(prefix, 100n)))
  })
})

describe('the toll (spec 6.4, 6.10)', () => {
  const H = 12, axis = 2
  const base = (0x1234567n >> 12n) << 12n
  const v1 = base + (1n << 11n) - 1n, v2 = base + (1n << 11n)
  const alice = seedPrefix(ZERO, axis), bob = seedPrefix(RANGE, axis)
  const a = computeAxisMerkleRoot(alice, axis, v1, v2)
  const b = computeAxisMerkleRoot(bob, axis, v1, v2)
  const G = hexToBytes(vector('golden-z-h12').G)

  it('gives two movers different roots at one boundary', () => {
    expect(a.height).toBe(H)
    expect(bytesToHex(a.root)).not.toBe(bytesToHex(b.root))
  })
  it('fails a copied proof under the copier\'s own seed', () => {
    expect(verifyAxisOpenings(bob, axis, v1, v2, a.root, a.openingsFor(G), G)).toBe(false)
  })
  it('separates identical subtrees on different axes', () => {
    const x = computeAxisMerkleRoot(seedPrefix(ZERO, 0), 0, v1, v2)
    expect(bytesToHex(x.root)).not.toBe(bytesToHex(a.root))
  })
  it('fails a fabricated tree on the sampled openings', () => {
    // A destination path hashed upward from forged siblings makes a root that
    // passes a destination-only check; the samples catch it.
    const fake = Array.from({ length: H }, (_, i) => sha256(new Uint8Array([102, 111, 114, 103, 101, i])))
    let cur = merkleLeaf(alice, v2)
    let i = Number(v2 - base)
    for (const s of fake) { cur = i % 2 === 0 ? merkleParent(cur, s) : merkleParent(s, cur); i = Math.floor(i / 2) }
    expect(verifyMerkleInclusion(alice, v2, fake, cur, H, base)).toBe(true)
    expect(verifyAxisOpenings(alice, axis, v1, v2, cur, Array(SIDESTEP_SAMPLES + 1).fill(fake), G)).toBe(false)
  })
})

describe('openings encoding (spec 8.5)', () => {
  const v = vector('zero-z-h5')
  const h = v.heights[2], paths = v.openings[2]
  it('round-trips, and reads exactly nine paths of h siblings', () => {
    const hex = encodeOpenings(paths.map((p) => p.map(hexToBytes)))
    expect(hex.length).toBe(64 * h * (SIDESTEP_SAMPLES + 1))
    expect(decodeOpenings(hex, h)!.map((p) => p.map(bytesToHex))).toEqual(paths)
    expect(decodeOpenings('', 0)).toEqual([])
  })
  it('rejects a v1 segment (one path) and anything off the fixed width', () => {
    const one = encodeOpenings([paths[0].map(hexToBytes)])
    expect(decodeOpenings(one, h)).toBeNull()
    expect(decodeOpenings(encodeOpenings(paths.map((p) => p.map(hexToBytes))) + 'ab', h)).toBeNull()
    expect(decodeOpenings('zz', 0)).toBeNull()
    expect(decodeOpenings('', 3)).toBeNull()
  })
})

describe('validCrossing (spec 6.3)', () => {
  it('accepts a source on the wall and a destination one past it, either way', () => {
    expect(validCrossing(7n, 8n)).toBe(true)
    expect(validCrossing(8n, 7n)).toBe(true)
    expect(validCrossing(5n, 5n)).toBe(true)
    expect(validCrossing(6n, 8n)).toBe(false)
    expect(validCrossing(7n, 9n)).toBe(false)
    // The landing is one past the HIGHEST wall toward the target (h7 for 7 -> 100), not the nearest.
    expect(sidestepLanding(7n, 100n)).toBe(64n)
    expect(sidestepLanding(7n, 8n)).toBe(8n)
    expect(sidestepLanding(8n, 7n)).toBe(7n)
  })
})

describe('computeSidestepProof and verifySidestepLevel1', () => {
  const prev = bytesToHex(RANGE)
  const x1 = 1023n, x2 = 1024n
  const y = 100n
  // z crosses the h6 wall at 480 upward: 479 touches it, 480 is one past.
  const z1 = 479n, z2 = 480n
  const seen: number[] = []
  const proof = computeSidestepProof(x1, y, z1, x2, y, z2, 0, prev, (f) => seen.push(f))
  const claim = claimOf(proof, [x1, y, z1], [x2, y, z2], prev)

  it('opens every moving axis nine times and none on the still one', () => {
    expect(proof.lcaHeights).toEqual([11, 0, 6])
    expect(proof.openings.x).toHaveLength(SIDESTEP_SAMPLES + 1)
    expect(proof.openings.y).toEqual([])
    expect(meetsPrice(proof.G, sidestepAttempts(proof.lcaHeights))).toBe(true)
  })
  it('reports progress that never goes backwards and ends at 1', () => {
    expect(seen.at(-1)).toBe(1)
    for (let i = 1; i < seen.length; i++) expect(seen[i]).toBeGreaterThanOrEqual(seen[i - 1])
  })
  it('verifies as published, with the openings as mp segments and the nonce as mn', () => {
    expect(verifySidestepLevel1(claim)).toEqual([])
    expect(verifySidestepLevel1({ ...claim, previousEventIdHex: bytesToHex(ZERO) })).toContain('openings:x')
    expect(verifySidestepLevel1({ ...claim, proofHash: '00'.repeat(32) })).toEqual(['proof'])
    expect(verifySidestepLevel1({ ...claim, openings: [encodeOpenings([proof.openings.x[0]]), '', claim.openings[2]] })).toContain('mp:x')
    expect(verifySidestepLevel1({ ...claim, from: { ...claim.from, x: 1022n } })).toContain('geometry:x')
  })
  it('rejects a nonce that misses the price', () => {
    const roots = [proof.merkleX, proof.merkleY, proof.merkleZ]
    const A = sidestepAttempts(proof.lcaHeights)
    let miss = 0n
    while (meetsPrice(sidestepGrindHash(RANGE, roots, miss), A)) miss++
    expect(verifySidestepLevel1({ ...claim, nonce: encodeNonce(miss) })).toContain('price')
  })
  it('rejects an mn tag that is not 16 lowercase hex characters', () => {
    expect(verifySidestepLevel1({ ...claim, nonce: claim.nonce!.toUpperCase() + 'F' })).toEqual(['mn'])
    expect(verifySidestepLevel1({ ...claim, nonce: '' })).toEqual(['mn'])
  })
  it('estimates the cost from the heights alone', () => {
    const c = estimateSidestepCost(x1, y, z1, x2, y, z2)
    expect(c.maxHeight).toBe(11)
    expect(c.totalHashes).toBe(2 ** 12 - 1 + 1 + 2 ** 7 - 1)
    expect(c.attempts).toBe((2 ** 11 + 2 ** 6) / 8)
  })
})

describe('version 2 sidesteps (spec 6.16)', () => {
  // The golden crossing again, published once as version 3 and once as version 2.
  const base = (0x1234567n >> 12n) << 12n
  const from = [5n, 7n, base + (1n << 11n) - 1n], to = [5n, 7n, base + (1n << 11n)]
  const prev = bytesToHex(ZERO)
  const proof = computeSidestepProof(from[0], from[1], from[2], to[0], to[1], to[2], 0, prev)
  const v3 = claimOf(proof, from, to, prev)
  const levels = levelsOf(seedPrefix(ZERO, AXIS_BYTE.z), base, 12)
  const v2Paths = [pathAt(levels, Number(to[2] - base)), ...v2Samples(proof.merkleZ, AXIS_BYTE.z, 12).map((i) => pathAt(levels, i))]
  const v2: SidestepClaim = { ...v3, openings: ['', '', encodeOpenings(v2Paths)], nonce: null }
  const listed = [...GRANDFATHERED_V2_SIDESTEPS][0]

  it('embeds the 36 listed ids', () => {
    expect(GRANDFATHERED_V2_SIDESTEPS.size).toBe(36)
    for (const id of GRANDFATHERED_V2_SIDESTEPS) expect(id).toMatch(/^[0-9a-f]{64}$/)
    expect(isGrandfatheredV2Sidestep(listed)).toBe(true)
    expect(isGrandfatheredV2Sidestep(listed.toUpperCase())).toBe(false)
    expect(isGrandfatheredV2Sidestep(undefined)).toBe(false)
  })
  it('rejects a version 2 proof, even given a nonce that meets the price', () => {
    expect(verifySidestepLevel1(v3)).toEqual([])
    // Its samples were drawn from the root, not from G.
    expect(verifySidestepLevel1({ ...v2, nonce: v3.nonce })).toEqual(['openings:z'])
  })
  it('rejects an unlisted event with no mn tag', () => {
    expect(verifySidestepLevel1({ ...v2, eventId: 'ab'.repeat(32) })).toEqual(['mn'])
    expect(verifySidestepLevel1(v2)).toEqual(['mn'])
  })
  it('accepts a listed event without checking its roots or openings', () => {
    expect(verifySidestepLevel1({ ...v2, eventId: listed })).toEqual([])
    expect(verifySidestepLevel1({ ...v2, eventId: listed, openings: ['', '', 'not openings'] })).toEqual([])
    // A missing tag passed straight through as undefined reads as absent too.
    expect(verifySidestepLevel1({ ...v2, eventId: listed, nonce: undefined as unknown as null })).toEqual([])
  })
  it('still checks everything else about a listed event', () => {
    const exempt = { ...v2, eventId: listed }
    expect(verifySidestepLevel1({ ...exempt, proofHash: '00'.repeat(32) })).toEqual(['proof'])
    expect(verifySidestepLevel1({ ...exempt, to: { ...exempt.to, z: to[2] + 1n } })).toContain('geometry:z')
    expect(verifySidestepLevel1({ ...exempt, lcaHeights: [0, 0, 11] })).toEqual(['hz'])
    expect(verifySidestepLevel1({ ...exempt, merkleRoots: [v3.merkleRoots[0], v3.merkleRoots[1], 'zz'] })).toEqual(['mr:z'])
  })
})

describe('a real listed event (fixtures/grandfathered_v2_sidestep.json)', () => {
  // bf4f8a3f..., a height-18 crossing on y audited at Level 2 before it was listed.
  const event: { id: string; tags: string[][] } = JSON.parse(readFileSync(new URL('./fixtures/grandfathered_v2_sidestep.json', import.meta.url), 'utf8'))
  const tag = (name: string): string | undefined => event.tags.find((t) => t[0] === name)?.[1]
  const from = coordToXyz(hexToCoord(tag('c')!)), to = coordToXyz(hexToCoord(tag('C')!))
  const claim: SidestepClaim = {
    from,
    to,
    plane: to.plane,
    previousEventIdHex: event.tags.find((t) => t[0] === 'e' && t[3] === 'previous')![1],
    merkleRoots: tag('mr')!.split(':') as [string, string, string],
    openings: tag('mp')!.split(':') as [string, string, string],
    nonce: tag('mn') ?? null,
    eventId: event.id,
    lcaHeights: [Number(tag('hx')), Number(tag('hy')), Number(tag('hz'))],
    proofHash: tag('proof')!,
  }

  it('is a version 2 proof at h18', () => {
    expect(claim.nonce).toBeNull()
    expect(claim.lcaHeights).toEqual([0, 18, 0])
    expect(findLcaHeight(from.y, to.y)).toBe(18)
    expect(alignedBase(from.y, 18)).toBe(alignedBase(to.y, 18))
  })
  it('passes as listed, and its proof hash is still checked', () => {
    expect(verifySidestepLevel1(claim)).toEqual([])
    expect(verifySidestepLevel1({ ...claim, proofHash: '00'.repeat(32) })).toEqual(['proof'])
  })
  it('fails under any other id', () => {
    expect(verifySidestepLevel1({ ...claim, eventId: 'f' + event.id.slice(1) })).toEqual(['mn'])
  })
  it('fails on its openings when given a nonce, as version 3', () => {
    const roots = claim.merkleRoots.map(hexToBytes)
    const found = findSidestepNonce(hexToBytes(claim.previousEventIdHex), roots, sidestepAttempts(claim.lcaHeights))!
    expect(verifySidestepLevel1({ ...claim, nonce: encodeNonce(found.nonce) })).toEqual(['openings:y'])
  })
})
