/**
 * sidestep.test.ts - the version 2 sidestep against the spec's reference.
 *
 * The golden vectors in fixtures/sidestep_v2.json were generated by the spec
 * repository's sidestep-reference.py (2026-09-07) and MUST match exactly:
 * seed prefixes, roots, sampled indices and every opening.
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { bytesToHex, hexToBytes, sha256 } from '../src/cantor.js'
import { alignedBase, findLcaHeight } from '../src/movement.js'
import {
  AXIS_BYTE,
  SIDESTEP_SAMPLES,
  computeAxisMerkleRoot,
  computeSidestepProof,
  decodeOpenings,
  encodeOpenings,
  estimateSidestepCost,
  leafHasher,
  merkleLeaf,
  merkleParent,
  sampleIndices,
  seedPrefix,
  sidestepLanding,
  validCrossing,
  verifyAxisOpenings,
  verifyMerkleInclusion,
  verifySidestepLevel1,
} from '../src/sidestep.js'

interface Vector {
  name: string
  prev: string
  axis: number
  v1: string
  v2: string
  base: string
  height: number
  prefix: string
  root: string
  samples: number[]
  openings: string[][]
}
const VECTORS: Vector[] = JSON.parse(readFileSync(new URL('./fixtures/sidestep_v2.json', import.meta.url), 'utf8'))
const ZERO = new Uint8Array(32)
const RANGE = new Uint8Array(32).map((_, i) => i)

describe('seedPrefix', () => {
  it('is the domain, the previous id, the axis byte and the pad: one block', () => {
    for (const v of VECTORS) expect(bytesToHex(seedPrefix(hexToBytes(v.prev), v.axis))).toBe(v.prefix)
    expect(seedPrefix(ZERO, 0).length).toBe(64)
    expect(() => seedPrefix(new Uint8Array(31), 0)).toThrow()
  })
})

describe('leafHasher', () => {
  it('resumes from the midstate to the same hash as one plain SHA-256', () => {
    const prefix = seedPrefix(RANGE, 2)
    const leaf = leafHasher(prefix)
    for (const value of [0n, 1n, 255n, 256n, 1n << 40n, (1n << 85n) - 1n]) {
      expect(bytesToHex(leaf(value))).toBe(bytesToHex(merkleLeaf(prefix, value)))
    }
  })
})

describe('computeAxisMerkleRoot', () => {
  for (const v of VECTORS) {
    it(`matches the reference on ${v.name} (h${v.height}): root, samples and every opening`, () => {
      const prefix = seedPrefix(hexToBytes(v.prev), v.axis)
      const r = computeAxisMerkleRoot(prefix, v.axis, BigInt(v.v1), BigInt(v.v2))
      expect(r.height).toBe(v.height)
      expect(bytesToHex(r.root)).toBe(v.root)
      expect(sampleIndices(r.root, v.axis, r.height)).toEqual(v.samples)
      expect(r.openings.map((p) => p.map(bytesToHex))).toEqual(v.openings)
      expect(verifyAxisOpenings(prefix, v.axis, BigInt(v.v1), BigInt(v.v2), r.root, r.openings)).toBe(true)
    })
  }

  it('matches a hand-built height-2 tree', () => {
    const prefix = seedPrefix(ZERO, 0)
    const h = [0n, 1n, 2n, 3n].map((n) => merkleLeaf(prefix, n))
    const expected = merkleParent(merkleParent(h[0], h[1]), merkleParent(h[2], h[3]))
    const r = computeAxisMerkleRoot(prefix, 0, 1n, 2n)
    expect(bytesToHex(r.root)).toBe(bytesToHex(expected))
    // Destination is leaf 2 (left of the right pair): siblings are h3 then p01.
    expect(bytesToHex(r.openings[0][0])).toBe(bytesToHex(h[3]))
    expect(bytesToHex(r.openings[0][1])).toBe(bytesToHex(merkleParent(h[0], h[1])))
    expect(r.openings).toHaveLength(SIDESTEP_SAMPLES + 1)
  })

  it('assembles the same openings when the height is above the kept levels', () => {
    // h18: two levels rebuilt under each opened leaf, the rest from what was kept.
    const prefix = seedPrefix(RANGE, 1)
    const base = 5n << 18n
    const v1 = base + (1n << 17n) - 1n, v2 = base + (1n << 17n)
    const r = computeAxisMerkleRoot(prefix, 1, v1, v2)
    expect(r.height).toBe(18)
    expect(verifyAxisOpenings(prefix, 1, v1, v2, r.root, r.openings)).toBe(true)
    // Every sampled path is the path of its own leaf, checked from scratch.
    const samples = sampleIndices(r.root, 1, 18)
    samples.forEach((idx, i) => expect(verifyMerkleInclusion(prefix, base + BigInt(idx), r.openings[i + 1], r.root, 18, base)).toBe(true))
  })

  it('handles trivial axes as a single seeded leaf with no openings', () => {
    const prefix = seedPrefix(ZERO, 0)
    const r = computeAxisMerkleRoot(prefix, 0, 100n, 100n)
    expect(r.height).toBe(0)
    expect(r.openings).toEqual([])
    expect(bytesToHex(r.root)).toBe(bytesToHex(merkleLeaf(prefix, 100n)))
  })
})

describe('the toll (spec 6.4, 6.10)', () => {
  const H = 12, axis = 2
  const base = (0x1234567n >> 12n) << 12n
  const v1 = base + (1n << 11n) - 1n, v2 = base + (1n << 11n)
  const alice = seedPrefix(ZERO, axis), bob = seedPrefix(RANGE, axis)
  const a = computeAxisMerkleRoot(alice, axis, v1, v2)
  const b = computeAxisMerkleRoot(bob, axis, v1, v2)

  it('gives two movers different roots at one boundary', () => {
    expect(a.height).toBe(H)
    expect(bytesToHex(a.root)).not.toBe(bytesToHex(b.root))
  })
  it('fails a copied proof under the copier\'s own seed', () => {
    expect(verifyAxisOpenings(bob, axis, v1, v2, a.root, a.openings)).toBe(false)
  })
  it('separates identical subtrees on different axes', () => {
    const x = computeAxisMerkleRoot(seedPrefix(ZERO, 0), 0, v1, v2)
    expect(bytesToHex(x.root)).not.toBe(bytesToHex(a.root))
  })
  it('fails a fabricated tree on the sampled openings', () => {
    // A destination path hashed upward from forged siblings makes a root that
    // passes a destination-only check; the samples catch it.
    const fake = Array.from({ length: H }, (_, i) => sha256(new Uint8Array([102, 111, 114, 103, 101, i])))
    let cur = merkleLeaf(alice, v2)
    let i = Number(v2 - base)
    for (const s of fake) { cur = i % 2 === 0 ? merkleParent(cur, s) : merkleParent(s, cur); i = Math.floor(i / 2) }
    expect(verifyMerkleInclusion(alice, v2, fake, cur, H, base)).toBe(true)
    expect(verifyAxisOpenings(alice, axis, v1, v2, cur, Array(SIDESTEP_SAMPLES + 1).fill(fake))).toBe(false)
  })
})

describe('openings encoding (spec 8.5)', () => {
  const v = VECTORS.find((x) => x.name === 'zero-z-h5')!
  it('round-trips, and reads exactly nine paths of h siblings', () => {
    const openings = v.openings.map((p) => p.map(hexToBytes))
    const hex = encodeOpenings(openings)
    expect(hex.length).toBe(64 * v.height * (SIDESTEP_SAMPLES + 1))
    expect(decodeOpenings(hex, v.height)!.map((p) => p.map(bytesToHex))).toEqual(v.openings)
    expect(decodeOpenings('', 0)).toEqual([])
  })
  it('rejects a v1 segment (one path) and anything off the fixed width', () => {
    const one = encodeOpenings([v.openings[0].map(hexToBytes)])
    expect(decodeOpenings(one, v.height)).toBeNull()
    expect(decodeOpenings(encodeOpenings(v.openings.map((p) => p.map(hexToBytes))) + 'ab', v.height)).toBeNull()
    expect(decodeOpenings('zz', 0)).toBeNull()
    expect(decodeOpenings('', 3)).toBeNull()
  })
})

describe('validCrossing (spec 6.3)', () => {
  it('accepts a source on the wall and a destination one past it, either way', () => {
    expect(validCrossing(7n, 8n)).toBe(true)
    expect(validCrossing(8n, 7n)).toBe(true)
    expect(validCrossing(5n, 5n)).toBe(true)
    expect(validCrossing(6n, 8n)).toBe(false)
    expect(validCrossing(7n, 9n)).toBe(false)
    // The landing is one past the HIGHEST wall toward the target (h7 for 7 -> 100), not the nearest.
    expect(sidestepLanding(7n, 100n)).toBe(64n)
    expect(sidestepLanding(7n, 8n)).toBe(8n)
    expect(sidestepLanding(8n, 7n)).toBe(7n)
  })
})

describe('computeSidestepProof and verifySidestepLevel1', () => {
  const prev = bytesToHex(RANGE)
  const x1 = 1023n, x2 = 1024n
  const y = 100n
  // z crosses the h6 wall at 480 upward: 479 touches it, 480 is one past.
  const z1 = 479n, z2 = 480n
  const proof = computeSidestepProof(x1, y, z1, x2, y, z2, 0, prev)

  it('opens every moving axis nine times and none on the still one', () => {
    expect(proof.lcaHeights).toEqual([11, 0, 6])
    expect(proof.openings.x).toHaveLength(SIDESTEP_SAMPLES + 1)
    expect(proof.openings.y).toEqual([])
  })
  it('verifies as published, with the openings encoded as mp segments', () => {
    const claim = {
      from: { x: x1, y, z: z1 }, to: { x: x2, y, z: z2 }, plane: 0 as const, previousEventIdHex: prev,
      merkleRoots: [bytesToHex(proof.merkleX), bytesToHex(proof.merkleY), bytesToHex(proof.merkleZ)] as [string, string, string],
      openings: [encodeOpenings(proof.openings.x), encodeOpenings(proof.openings.y), encodeOpenings(proof.openings.z)] as [string, string, string],
      lcaHeights: proof.lcaHeights,
      proofHash: proof.proofHash,
    }
    expect(verifySidestepLevel1(claim)).toEqual([])
    expect(verifySidestepLevel1({ ...claim, previousEventIdHex: bytesToHex(ZERO) })).toContain('openings:x')
    expect(verifySidestepLevel1({ ...claim, proofHash: '00'.repeat(32) })).toEqual(['proof'])
    expect(verifySidestepLevel1({ ...claim, openings: [encodeOpenings([proof.openings.x[0]]), '', claim.openings[2]] })).toContain('mp:x')
    expect(verifySidestepLevel1({ ...claim, from: { ...claim.from, x: 1022n } })).toContain('geometry:x')
  })
  it('estimates the cost from the heights alone', () => {
    const c = estimateSidestepCost(x1, y, z1, x2, y, z2)
    expect(c.maxHeight).toBe(11)
    expect(c.totalHashes).toBe(2 ** 12 - 1 + 1 + 2 ** 7 - 1)
  })
})
