#!/usr/bin/env node
/**
 * Regenerates src/grandfathered_v2_sidesteps.ts from the spec repository's
 * grandfathered-v2-sidesteps.txt (CYBERSPACE_V2.md section 6.16).
 *
 *   node scripts/grandfathered.mjs [path to a cyberspace clone] [ref]
 *
 * Defaults: ../cyberspace and origin/master. The list is read from the ref
 * with git show, never from the clone's working tree, and the header of the
 * generated file names the commit the ref resolved to. Fetch the clone first.
 */

import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const LIST = 'grandfathered-v2-sidesteps.txt'
const OUT = new URL('../src/grandfathered_v2_sidesteps.ts', import.meta.url)
const [repo = '../cyberspace', ref = 'origin/master'] = process.argv.slice(2)

const git = (...args) => execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8' })
const commit = git('rev-parse', `${ref}^{commit}`).trim()
const text = git('show', `${commit}:${LIST}`)

// Section 6.16: lines starting with # are comments; every other non-empty line
// starts with a 64-character lowercase hex event id, and the rest is commentary.
const entries = []
for (const line of text.split('\n')) {
  const trimmed = line.trim()
  if (trimmed === '' || trimmed.startsWith('#')) continue
  const [id, ...rest] = trimmed.split(/\s+/)
  if (!/^[0-9a-f]{64}$/.test(id)) throw new Error(`not a 64-hex event id: ${trimmed}`)
  entries.push({ id, note: rest.join(' ') })
}
if (new Set(entries.map((e) => e.id)).size !== entries.length) throw new Error(`${LIST} lists an id twice`)

const out = `/**
 * GENERATED by scripts/grandfathered.mjs. Do not edit by hand; rerun it.
 *
 * Source: arkin0x/cyberspace ${commit}, ${LIST}
 *
 * The version 2 sidesteps exempt under CYBERSPACE_V2.md section 6.16, by
 * event id: an event listed here carries no \`mn\` tag, and a verifier accepts
 * its Merkle roots and openings without re-checking them and checks
 * everything else. Commentary per line: pubkey, created_at, heights (x,y,z),
 * audit.
 */
export const GRANDFATHERED_V2_SIDESTEPS: ReadonlySet<string> = new Set([
${entries.map((e) => `  '${e.id}', // ${e.note}`).join('\n')}
])
`
writeFileSync(OUT, out)
console.log(`${entries.length} ids from ${commit} -> src/grandfathered_v2_sidesteps.ts`)
